version: '3'
services:
 db:
  build:
    context: .
    dockerfile: mysql_dockerfile
  image: mysql:docker
  container_name: database
  ports:
    - 3306:3306
 tomcat:
  build:
    context: .
    dockerfile: tomcat_dockerfile
  image: tomcat:docker
  container_name: webserver
  depends_on:
    - db
  ports:
    - 8081:8080
  links:
    - db:mysql
